# ref: https://sagiegurari.github.io/cargo-make/
[env]
# DOCKER_REPO = "ecfront"
# DOCKER_VERSION = "${CARGO_MAKE_PROJECT_VERSION}"

[tasks.format]
workspace = true
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--emit=files"]

[tasks.clean]
workspace = true
command = "cargo"
args = ["clean"]

[tasks.check]
workspace = true
dependencies = ["format"]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-features"]


[tasks.build-spacegate-k8s]
workspace = false
command = "cargo"
args = ["build", "--bin", "spacegate", "--release", "--features", "build-k8s"]

[tasks.build-spacegate-linux]
workspace = false
command = "cargo"
args = ["build", "--bin", "spacegate", "--release", "--features", "dylib"]

[tasks.build-k8s-docker]
workspace = false
dependencies = ["build-spacegate-k8s"]
script = '''
echo ${CARGO_MAKE_CRATE_VERSION}
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
cp target/release/spacegate resource/docker/spacegate
docker build -t ${DOCKER_REPO}/spacegate:${DOCKER_VERSION} resource/docker/spacegate
rm resource/docker/spacegate/spacegate
cd ${CARGO_MAKE_WORKING_DIRECTORY}
'''


[tasks.install-spacegate]
workspace = false
dependencies = ["build-spacegate-linux"]
script = { file = "resource/install/install.sh" }

[tasks.build-spacegate-admin]
workspace = false
command = "cargo"
args = ["build", "--bin", "spacegate-admin-server", "--release"]

[tasks.install-spacegate-admin]
workspace = false
dependencies = ["build-spacegate-admin"]
script = { file = "resource/install/install-admin.sh" }


[tasks.build-sdk]
workspace = false
script = '''
cd sdk/admin-client;
npm run build-model;
'''


[tasks.package-ext-redis]
workspace = false
command = "cargo"
args = ["package", "-p", "spacegate-ext-redis"]

[tasks.publish-ext-redis]
workspace = false
dependencies = ["package-ext-redis"]
command = "cargo"
args = ["publish", "-p", "spacegate-ext-redis"]

[tasks.package-ext-axum]
workspace = false
command = "cargo"
args = ["package", "-p", "spacegate-ext-axum"]

[tasks.publish-ext-axum]
workspace = false
dependencies = ["package-ext-axum"]
command = "cargo"
args = ["publish", "-p", "spacegate-ext-axum"]

[tasks.package-kernel]
workspace = false
dependencies = ["publish-ext-axum", "publish-ext-redis"]
command = "cargo"
args = ["package", "-p", "spacegate-kernel"]

[tasks.publish-kernel]
workspace = false
dependencies = ["package-kernel"]
command = "cargo"
args = ["publish", "-p", "spacegate-kernel"]

[tasks.package-model]
workspace = false
dependencies = ["publish-ext-axum", "publish-ext-redis"]
command = "cargo"
args = ["package", "-p", "spacegate-model"]

[tasks.publish-model]
workspace = false
dependencies = ["package-model"]
command = "cargo"
args = ["publish", "-p", "spacegate-model"]

[tasks.package-plugin]
workspace = false
dependencies = ["publish-kernel", "publish-model"]
command = "cargo"
args = ["package", "-p", "spacegate-model"]

[tasks.publish-plugin]
workspace = false
dependencies = ["package-plugin"]
command = "cargo"
args = ["publish", "-p", "spacegate-plugin"]

[tasks.package-config]
workspace = false
dependencies = ["publish-ext-axum", "publish-ext-redis", "publish-model"]
command = "cargo"
args = ["package", "-p", "spacegate-config"]

[tasks.publish-config]
workspace = false
dependencies = ["package-config"]
command = "cargo"
args = ["publish", "-p", "spacegate-config"]

[tasks.package-shell]
workspace = false
dependencies = [
    "publish-ext-axum",
    "publish-ext-redis",
    "publish-model",
    "publish-plugin",
    "publish-config",
    "publish-kernel",
]
command = "cargo"
args = ["package", "-p", "spacegate-shell"]

[tasks.publish-shell]
workspace = false
dependencies = ["package-shell"]
command = "cargo"
args = ["publish", "-p", "spacegate-shell"]

[tasks.package-spacegate]
workspace = false
dependencies = [
    "publish-shell"
]
command = "cargo"
args = ["package", "-p", "spacegate"]

[tasks.publish-spacegate]
workspace = false
dependencies = ["package-spacegate"]
command = "cargo"
args = ["publish", "-p", "spacegate"]

[tasks.publish]
workspace = false
dependencies = [
    "publish-ext-axum",
    "publish-ext-redis",
    "publish-model",
    "publish-plugin",
    "publish-config",
    "publish-kernel",
    "publish-shell",
    "publish-spacegate",
]
