[[gateways]]
name = "new gateway"
plugins = []

[gateways.parameters]
ignore_tls_verification = false

[[gateways.listeners]]
name = "new listener"
port = 9090

[gateways.listeners.protocol]
type = "http"

[[gateways.routes]]
route_name = "1"
plugins = []
priority = 1

[[gateways.routes.rules]]

[[gateways.routes.rules.matches]]

[gateways.routes.rules.matches.path]
kind = "Prefix"
value = "/api"

[[gateways.routes.rules.plugins]]
uid = 3995583412000053383
code = "rewrite"
spec = { path = { kind = "test", value = "test" } }

[[gateways.routes.rules.plugins]]
[gateways.routes.rules.plugins.spec]

[[gateways.routes.rules.backends]]
port = 443
timeout_ms = 5000
protocol = "https"
weight = 1
plugins = []

[gateways.routes.rules.backends.host]
kind = "Host"
host = "baidu.com"

[[gateways.routes]]
route_name = "2"
plugins = []
rules = []
priority = 1

[plugins]
named = []
mono = []
