name: Publish Admin Client package

on:
  push:
    branches:
      - dev
      - master
    paths:
      - "sdk/admin-client/**"
      - ".github/workflows/publish_client.yml"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: cd sdk/admin-client && npm ci

      - name: Build
        run: cd sdk/admin-client && npm run build

      - name: Publish
        run: cd sdk/admin-client && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
